spring:
  ai:
    zhipuai:
      api-key: ${ZHIPUAI_API_KEY}
#    ollama:
#      chat:
#        options:
#          model: qwen3
#      embedding:
#        options:
#          model: qwen3-embedding
#      base-url: http://localhost:11434
    vectorstore:
      redis:
        initialize-schema: true
        index-name: custom-index
        prefix: custom-prefix
    mcp:
      client:
        type: ASYNC
        stdio:
          servers-configuration: classpath:mcp-servers.json
#    chat:
#      ui:
#        rag:
#          template: |
#            <query>
#
#            上下文信息如下。
#
#            ---------------------
#            <question_answer_context>
#            ---------------------
#
#            如果没有上下文信息，直接回答问题
#
#            如果有上下文信息，根据上下文信息回答问题。并遵循以下规则：
#            1. 如果答案不在上下文中，则直接说明您不知道。
#            2. 避免使用"根据上下文..."或"提供的信息..."之类的表述。
#            3. 每句话结尾使用"喵~"、”喵内~“等。
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 9379
      password: 123456

server:
  tomcat:
    max-swallow-size: 2MB
    disable-upload-timeout: false

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG